//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mynfo.Resources1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mynfo.Resources1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My active accounts.
        /// </summary>
        public static string ActiveAccounts {
            get {
                return ResourceManager.GetString("ActiveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add network.
        /// </summary>
        public static string AddNetwork {
            get {
                return ResourceManager.GetString("AddNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profiles to Box.
        /// </summary>
        public static string AddPBox {
            get {
                return ResourceManager.GetString("AddPBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profiles.
        /// </summary>
        public static string AddProfiles {
            get {
                return ResourceManager.GetString("AddProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add profile to social network.
        /// </summary>
        public static string AddPSocialMedia {
            get {
                return ResourceManager.GetString("AddPSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 years old.
        /// </summary>
        public static string AgePlaceHolder {
            get {
                return ResourceManager.GetString("AgePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the Boxes that you configure and manipulate from now on will be reflected in your myTAG..
        /// </summary>
        public static string AllConfigSticker {
            get {
                return ResourceManager.GetString("AllConfigSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Code 2:.
        /// </summary>
        public static string AlphaCode2 {
            get {
                return ResourceManager.GetString("AlphaCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Code 3:.
        /// </summary>
        public static string AlphaCode3 {
            get {
                return ResourceManager.GetString("AlphaCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and stick it to the back of your phone..
        /// </summary>
        public static string AndStick {
            get {
                return ResourceManager.GetString("AndStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  years old.
        /// </summary>
        public static string Anios {
            get {
                return ResourceManager.GetString("Anios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the network permanently from the box?.
        /// </summary>
        public static string AskDeleteNetworkFromBox {
            get {
                return ResourceManager.GetString("AskDeleteNetworkFromBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borders.
        /// </summary>
        public static string Borders {
            get {
                return ResourceManager.GetString("Borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box list.
        /// </summary>
        public static string BoxList {
            get {
                return ResourceManager.GetString("BoxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box name.
        /// </summary>
        public static string BoxName {
            get {
                return ResourceManager.GetString("BoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian:.
        /// </summary>
        public static string Brazilian {
            get {
                return ResourceManager.GetString("Brazilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital:.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was changed successfully..
        /// </summary>
        public static string ChagePasswordConfirm {
            get {
                return ResourceManager.GetString("ChagePasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch the image to change it.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        public static string ChooseTypeProfile {
            get {
                return ResourceManager.GetString("ChooseTypeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIOC:.
        /// </summary>
        public static string CIOC {
            get {
                return ResourceManager.GetString("CIOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorless.
        /// </summary>
        public static string Colorless {
            get {
                return ResourceManager.GetString("Colorless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your myTAG ready ....
        /// </summary>
        public static string ConfigSticker {
            get {
                return ResourceManager.GetString("ConfigSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myTAG configured!.
        /// </summary>
        public static string ConfigStickerRi {
            get {
                return ResourceManager.GetString("ConfigStickerRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure myTAG.
        /// </summary>
        public static string ConfigureTAG {
            get {
                return ResourceManager.GetString("ConfigureTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password confirm....
        /// </summary>
        public static string ConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a confirm..
        /// </summary>
        public static string ConfirmValidation {
            get {
                return ResourceManager.GetString("ConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirm does not match..
        /// </summary>
        public static string ConfirmValidation2 {
            get {
                return ResourceManager.GetString("ConfirmValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on your internet settings..
        /// </summary>
        public static string ConnectionError1 {
            get {
                return ResourceManager.GetString("ConnectionError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check you internet connection..
        /// </summary>
        public static string ConnectionError2 {
            get {
                return ResourceManager.GetString("ConnectionError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create email profile.
        /// </summary>
        public static string CreateProfileEmail {
            get {
                return ResourceManager.GetString("CreateProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create phone profile .
        /// </summary>
        public static string CreateProfilePhone {
            get {
                return ResourceManager.GetString("CreateProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian:.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password.
        /// </summary>
        public static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark blue.
        /// </summary>
        public static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark green.
        /// </summary>
        public static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Box.
        /// </summary>
        public static string DefaultBox {
            get {
                return ResourceManager.GetString("DefaultBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the box permanently, do you want to continue?.
        /// </summary>
        public static string DeleteBoxNotification {
            get {
                return ResourceManager.GetString("DeleteBoxNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonym:.
        /// </summary>
        public static string Demonym {
            get {
                return ResourceManager.GetString("Demonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box details.
        /// </summary>
        public static string DetailBox {
            get {
                return ResourceManager.GetString("DetailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show again..
        /// </summary>
        public static string DoNotShowAgain {
            get {
                return ResourceManager.GetString("DoNotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch:.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit email profile.
        /// </summary>
        public static string EditEmail {
            get {
                return ResourceManager.GetString("EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit network.
        /// </summary>
        public static string EditNetwork {
            get {
                return ResourceManager.GetString("EditNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit phone profile.
        /// </summary>
        public static string EditPhone {
            get {
                return ResourceManager.GetString("EditPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile data.
        /// </summary>
        public static string EditProfileData {
            get {
                return ResourceManager.GetString("EditProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email profile list.
        /// </summary>
        public static string EmailProfileList {
            get {
                return ResourceManager.GetString("EmailProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an email.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid email.
        /// </summary>
        public static string EmailValidation2 {
            get {
                return ResourceManager.GetString("EmailValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have networks added to this box yet.
        /// </summary>
        public static string EmptyBox {
            get {
                return ResourceManager.GetString("EmptyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred, please try again later.
        /// </summary>
        public static string ErrorAddProfile {
            get {
                return ResourceManager.GetString("ErrorAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can&apos;t be changed, please try latter.
        /// </summary>
        public static string ErrorChangingPassword {
            get {
                return ResourceManager.GetString("ErrorChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        public static string EscanQR {
            get {
                return ResourceManager.GetString("EscanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@domain.com.
        /// </summary>
        public static string ExampleEmail {
            get {
                return ResourceManager.GetString("ExampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Facebook profiles.
        /// </summary>
        public static string FacebookProfileList {
            get {
                return ResourceManager.GetString("FacebookProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first name.
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a first name.
        /// </summary>
        public static string FirstNameValidation {
            get {
                return ResourceManager.GetString("FirstNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French:.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From camera.
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuchsia.
        /// </summary>
        public static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German:.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GINI:.
        /// </summary>
        public static string GINI {
            get {
                return ResourceManager.GetString("GINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number has whatsapp..
        /// </summary>
        public static string HaveWhats {
            get {
                return ResourceManager.GetString("HaveWhats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I read another myTAG?.
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold your Phone near the myTAG..
        /// </summary>
        public static string HoldYourPhone {
            get {
                return ResourceManager.GetString("HoldYourPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does mynfo work?.
        /// </summary>
        public static string HowMynfoWorks {
            get {
                return ResourceManager.GetString("HowMynfoWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian:.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese:.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1:.
        /// </summary>
        public static string LabelStep1 {
            get {
                return ResourceManager.GetString("LabelStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2:.
        /// </summary>
        public static string LabelStep2 {
            get {
                return ResourceManager.GetString("LabelStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3:.
        /// </summary>
        public static string LabelStep3 {
            get {
                return ResourceManager.GetString("LabelStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must add a valid side..
        /// </summary>
        public static string LadaValidation {
            get {
                return ResourceManager.GetString("LadaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the last name....
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a last name.
        /// </summary>
        public static string LastNameValidation {
            get {
                return ResourceManager.GetString("LastNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light blue.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lilac.
        /// </summary>
        public static string Lilac {
            get {
                return ResourceManager.GetString("Lilac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile URL.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a url.
        /// </summary>
        public static string LinkValidation {
            get {
                return ResourceManager.GetString("LinkValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manhattan, Nueva York, EE. UU..
        /// </summary>
        public static string LocationPlaceHolder {
            get {
                return ResourceManager.GetString("LocationPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password incorrect..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginSession {
            get {
                return ResourceManager.GetString("LoginSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi!, I met you through mynfo, I&apos;m .
        /// </summary>
        public static string MessageWhatsApp {
            get {
                return ResourceManager.GetString("MessageWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My accounts in.
        /// </summary>
        public static string MyAccounts {
            get {
                return ResourceManager.GetString("MyAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string MyLanguages {
            get {
                return ResourceManager.GetString("MyLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string MyProfiles {
            get {
                return ResourceManager.GetString("MyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My QR.
        /// </summary>
        public static string MyQR {
            get {
                return ResourceManager.GetString("MyQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This myTAG is linked to another user!.
        /// </summary>
        public static string MyTAGValidation {
            get {
                return ResourceManager.GetString("MyTAGValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string NameProfile {
            get {
                return ResourceManager.GetString("NameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a name.
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Name:.
        /// </summary>
        public static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network added to the box .
        /// </summary>
        public static string NetworkAdded {
            get {
                return ResourceManager.GetString("NetworkAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks list.
        /// </summary>
        public static string NetworksList {
            get {
                return ResourceManager.GetString("NetworksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Box.
        /// </summary>
        public static string NewBox {
            get {
                return ResourceManager.GetString("NewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new password....
        /// </summary>
        public static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NickNamePH {
            get {
                return ResourceManager.GetString("NickNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Boxes yet..
        /// </summary>
        public static string NoBoxesYet {
            get {
                return ResourceManager.GetString("NoBoxesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business, Personal, Friends..
        /// </summary>
        public static string NProfilePlaceH {
            get {
                return ResourceManager.GetString("NProfilePlaceH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell number.
        /// </summary>
        public static string NumberPhone {
            get {
                return ResourceManager.GetString("NumberPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone number..
        /// </summary>
        public static string NumberValidation {
            get {
                return ResourceManager.GetString("NumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Code:.
        /// </summary>
        public static string NumericCode {
            get {
                return ResourceManager.GetString("NumericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation:.
        /// </summary>
        public static string OccupationLabel {
            get {
                return ResourceManager.GetString("OccupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology Engineer..
        /// </summary>
        public static string OccupationPlaceHolder {
            get {
                return ResourceManager.GetString("OccupationPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a password.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have at least six (6) characters.
        /// </summary>
        public static string PasswordValidation2 {
            get {
                return ResourceManager.GetString("PasswordValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian:.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone..
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone profile list.
        /// </summary>
        public static string PhoneProfileList {
            get {
                return ResourceManager.GetString("PhoneProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a phone number.
        /// </summary>
        public static string PhoneValidation {
            get {
                return ResourceManager.GetString("PhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number must contain 10 digits.
        /// </summary>
        public static string PhoneValidation2 {
            get {
                return ResourceManager.GetString("PhoneValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population:.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese:.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile details.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user was created by a social network, to make a change you must make it from that same social network.
        /// </summary>
        public static string ProfileELabel {
            get {
                return ResourceManager.GetString("ProfileELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mynfo Profile.
        /// </summary>
        public static string ProfileMynfo {
            get {
                return ResourceManager.GetString("ProfileMynfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not created any profile of this type yet.
        /// </summary>
        public static string ProfileNull {
            get {
                return ResourceManager.GetString("ProfileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone profile.
        /// </summary>
        public static string ProfilePhone {
            get {
                return ResourceManager.GetString("ProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My active profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string PutEmail {
            get {
                return ResourceManager.GetString("PutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        public static string QR {
            get {
                return ResourceManager.GetString("QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QR code will allow you to share your default box in any browser..
        /// </summary>
        public static string QRForWhat {
            get {
                return ResourceManager.GetString("QRForWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a QR code from mynfo..
        /// </summary>
        public static string QRMynfo {
            get {
                return ResourceManager.GetString("QRMynfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read both steps before configurating your myTAG..
        /// </summary>
        public static string ReadInstructions {
            get {
                return ResourceManager.GetString("ReadInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Scan..
        /// </summary>
        public static string ReadyToScan {
            get {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ReceivedBoxes {
            get {
                return ResourceManager.GetString("ReceivedBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me in this device.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search..
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color.
        /// </summary>
        public static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send an email so you can log in..
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something was wrong, please try again later.
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to take the image?.
        /// </summary>
        public static string SourceImageQuestion {
            get {
                return ResourceManager.GetString("SourceImageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish:.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statics.
        /// </summary>
        public static string Statics {
            get {
                return ResourceManager.GetString("Statics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Configure myTAG button, wait until the phone stops vibrating and you see the &quot;ready to scan&quot; screen, then place your myTAG to the upper back of your phone..
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your myTAG pressed against the phone until it vibrates again and you see the confirmation screen. 
        ///
        ///NOTE: The area of your phone where you have to place your myTAG in order to congifure it may vary dependeing on the phone model..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your myTAG glued to the phone until it vibrates again and you see the confirmation screen..
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subregion:.
        /// </summary>
        public static string Subregion {
            get {
                return ResourceManager.GetString("Subregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you have your myTAG at hand..
        /// </summary>
        public static string SureTAG {
            get {
                return ResourceManager.GetString("SureTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure myTAG.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t have it yet, buy it at.
        /// </summary>
        public static string TakeinStore {
            get {
                return ResourceManager.GetString("TakeinStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is invalid..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was created, now you can login with this email and password.
        /// </summary>
        public static string UserRegisteredMessage {
            get {
                return ResourceManager.GetString("UserRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user doesn´t have boxes created..
        /// </summary>
        public static string UserWithoutBoxes {
            get {
                return ResourceManager.GetString("UserWithoutBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections: .
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you have a little walk through the app..
        /// </summary>
        public static string Walktrough {
            get {
                return ResourceManager.GetString("Walktrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to mynfo!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Whatsapp profiles.
        /// </summary>
        public static string WhatsappProfileList {
            get {
                return ResourceManager.GetString("WhatsappProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It already exists an account with that email, try again with a different one.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
